In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings

## load the data set

In [34]:
df = pd.read_csv(r'C:\CODING\MACHINE LEARNING\ford.csv')

In [35]:
df

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,Fiesta,2017,12000,Automatic,15944,Petrol,150,57.7,1.0
1,Focus,2018,14000,Manual,9083,Petrol,150,57.7,1.0
2,Focus,2017,13000,Manual,12456,Petrol,150,57.7,1.0
3,Fiesta,2019,17500,Manual,10460,Petrol,145,40.3,1.5
4,Fiesta,2019,16500,Automatic,1482,Petrol,145,48.7,1.0
...,...,...,...,...,...,...,...,...,...
17961,B-MAX,2017,8999,Manual,16700,Petrol,150,47.1,1.4
17962,B-MAX,2014,7499,Manual,40700,Petrol,30,57.7,1.0
17963,Focus,2015,9999,Manual,7010,Diesel,20,67.3,1.6
17964,KA,2018,8299,Manual,5007,Petrol,145,57.7,1.2
17965,Focus,2015,8299,Manual,5007,Petrol,22,57.7,1.0

## EDA

In [36]:
df.shape

(17966, 9)

In [37]:
df.isnull().sum()

model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [38]:
df.duplicated().sum()

np.int64(154)

In [39]:
df.columns

Index(['model', 'year', 'price', 'transmission', 'mileage', 'fuelType', 'tax',
       'mpg', 'engineSize'],
      dtype='str')

In [40]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17966 entries, 0 to 17965
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         17966 non-null  str
 1   year          17966 non-null  int64
 2   price         17966 non-null  int64
 3   transmission  17966 non-null  str
 4   mileage       17966 non-null  int64
 5   fuelType      17966 non-null  str
 6   tax           17966 non-null  int64
 7   mpg           17966 non-null  float64
 8   engineSize    17966 non-null  float64
dtypes: float64(2), int64(4), str(3)
memory usage: 1.2 MB

In [41]:
df = df.drop_duplicates(subset=['model', 'year', 'price', 'transmission', 'mileage', 'fuelType', 'tax',
       'mpg', 'engineSize'])

In [42]:
df.duplicated().sum()

np.int64(0)

In [43]:
x = df.drop(['price'], axis = 1)
y = df['price']

## APPLYING ONE HOT ENCODING TO CONVERRT STR INTO NUMERIC TERM

In [44]:
one_hot_encoding = pd.get_dummies(x,columns=['model','transmission','fuelType'],drop_first=True)

In [45]:
one_hot_encoding = one_hot_encoding.astype(int)

In [46]:
one_hot_encoding

,year,mileage,tax,mpg,engineSize,model_ C-MAX,model_ EcoSport,model_ Edge,model_ Escort,model_ Fiesta,...,model_ Tourneo Connect,model_ Tourneo Custom,model_ Transit Tourneo,model_Focus,transmission_Manual,transmission_Semi-Auto,fuelType_Electric,fuelType_Hybrid,fuelType_Other,fuelType_Petrol
0,2017,15944,150,57,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
1,2018,9083,150,57,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
2,2017,12456,150,57,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
3,2019,10460,145,40,1,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,1
4,2019,1482,145,48,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17961,2017,16700,150,47,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
17962,2014,40700,30,57,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
17963,2015,7010,20,67,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
17964,2018,5007,145,57,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
17965,2015,5007,22,57,1,0,0,0,0,0,...,0,0,0,1,1,0,0,0,0,1

In [47]:
one_hot_encoding.info()

<class 'pandas.DataFrame'>
Index: 17812 entries, 0 to 17965
Data columns (total 34 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   year                          17812 non-null  int64
 1   mileage                       17812 non-null  int64
 2   tax                           17812 non-null  int64
 3   mpg                           17812 non-null  int64
 4   engineSize                    17812 non-null  int64
 5   model_ C-MAX                  17812 non-null  int64
 6   model_ EcoSport               17812 non-null  int64
 7   model_ Edge                   17812 non-null  int64
 8   model_ Escort                 17812 non-null  int64
 9   model_ Fiesta                 17812 non-null  int64
 10  model_ Focus                  17812 non-null  int64
 11  model_ Fusion                 17812 non-null  int64
 12  model_ Galaxy                 17812 non-null  int64
 13  model_ Grand C-MAX            17812 non-null  int64
 14  model_ Grand Tourneo Connect  17812 non-null  int64
 15  model_ KA                     17812 non-null  int64
 16  model_ Ka+                    17812 non-null  int64
 17  model_ Kuga                   17812 non-null  int64
 18  model_ Mondeo                 17812 non-null  int64
 19  model_ Mustang                17812 non-null  int64
 20  model_ Puma                   17812 non-null  int64
 21  model_ Ranger                 17812 non-null  int64
 22  model_ S-MAX                  17812 non-null  int64
 23  model_ Streetka               17812 non-null  int64
 24  model_ Tourneo Connect        17812 non-null  int64
 25  model_ Tourneo Custom         17812 non-null  int64
 26  model_ Transit Tourneo        17812 non-null  int64
 27  model_Focus                   17812 non-null  int64
 28  transmission_Manual           17812 non-null  int64
 29  transmission_Semi-Auto        17812 non-null  int64
 30  fuelType_Electric             17812 non-null  int64
 31  fuelType_Hybrid               17812 non-null  int64
 32  fuelType_Other                17812 non-null  int64
 33  fuelType_Petrol               17812 non-null  int64
dtypes: int64(34)
memory usage: 4.8 MB

## NOW DOING LABEL ENCODING

In [48]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

columns = ['model','transmission','fuelType']
xlabel = x.copy()
label_encoder = {}

for col in columns:
    le = LabelEncoder()
    xlabel[col] = le.fit_transform(xlabel[col].astype(str)) #convert to str into null values 
    
    label_encoder[col] = le

In [49]:
xlabel

       model  year  transmission  mileage  fuelType  tax   mpg  engineSize
0          5  2017             0    15944         4  150  57.7         1.0
1          6  2018             1     9083         4  150  57.7         1.0
2          6  2017             1    12456         4  150  57.7         1.0
3          5  2019             1    10460         4  145  40.3         1.5
4          5  2019             0     1482         4  145  48.7         1.0
...      ...   ...           ...      ...       ...  ...   ...         ...
17961      0  2017             1    16700         4  150  47.1         1.4
17962      0  2014             1    40700         4   30  57.7         1.0
17963      6  2015             1     7010         0   20  67.3         1.6
17964     11  2018             1     5007         4  145  57.7         1.2
17965     23  2015             1     5007         4   22  57.7         1.0

[17812 rows x 8 columns]

## DOING STANDARD SCLAING WITH THE HELP OF ONE_HOT_ENCODING

In [50]:
one_hot_encoding.columns

Index(['year', 'mileage', 'tax', 'mpg', 'engineSize', 'model_ C-MAX',
       'model_ EcoSport', 'model_ Edge', 'model_ Escort', 'model_ Fiesta',
       'model_ Focus', 'model_ Fusion', 'model_ Galaxy', 'model_ Grand C-MAX',
       'model_ Grand Tourneo Connect', 'model_ KA', 'model_ Ka+',
       'model_ Kuga', 'model_ Mondeo', 'model_ Mustang', 'model_ Puma',
       'model_ Ranger', 'model_ S-MAX', 'model_ Streetka',
       'model_ Tourneo Connect', 'model_ Tourneo Custom',
       'model_ Transit Tourneo', 'model_Focus', 'transmission_Manual',
       'transmission_Semi-Auto', 'fuelType_Electric', 'fuelType_Hybrid',
       'fuelType_Other', 'fuelType_Petrol'],
      dtype='str')

In [51]:
from sklearn.preprocessing import StandardScaler

In [53]:
numeric_col = ['year','mileage','tax','mpg','engineSize']
scaler = StandardScaler()

one_hot_encoding[numeric_col] = scaler.fit_transform(one_hot_encoding[numeric_col])

In [54]:
one_hot_encoding

,year,mileage,tax,mpg,engineSize,model_ C-MAX,model_ EcoSport,model_ Edge,model_ Escort,model_ Fiesta,...,model_ Tourneo Connect,model_ Tourneo Custom,model_ Transit Tourneo,model_Focus,transmission_Manual,transmission_Semi-Auto,fuelType_Electric,fuelType_Hybrid,fuelType_Other,fuelType_Petrol
0,0.067059,-0.382994,0.591380,-0.042291,-0.446958,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
1,0.554393,-0.736317,0.591380,-0.042291,-0.446958,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
2,0.067059,-0.562616,0.591380,-0.042291,-0.446958,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
3,1.041726,-0.665405,0.510777,-1.720193,-0.446958,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,1
4,1.041726,-1.127749,0.510777,-0.930592,-0.446958,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17961,0.067059,-0.344061,0.591380,-1.029292,-0.446958,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
17962,-1.394942,0.891875,-1.343079,-0.042291,-0.446958,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
17963,-0.907608,-0.843071,-1.504284,0.944711,-0.446958,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
17964,0.554393,-0.946220,0.510777,-0.042291,-0.446958,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
17965,-0.907608,-0.946220,-1.472043,-0.042291,-0.446958,0,0,0,0,0,...,0,0,0,1,1,0,0,0,0,1

## NOW DOING  XLABEL-ENCODING TO CONVERT LARGE NUMBER INTO SMALL NUMERIC

In [56]:
xlabel[['model', 'year', 'transmission', 'mileage', 'fuelType', 'tax', 'mpg',
       'engineSize']] = scaler.fit_transform(xlabel[['model', 'year', 'transmission', 'mileage', 'fuelType', 'tax', 'mpg',
       'engineSize']])

In [57]:
xlabel

,model,year,transmission,mileage,fuelType,tax,mpg,engineSize
0,-0.460281,0.067059,-2.667947,-0.382994,0.688206,0.591380,-0.020597,-0.810561
1,-0.210828,0.554393,0.042455,-0.736317,0.688206,0.591380,-0.020597,-0.810561
2,-0.210828,0.067059,0.042455,-0.562616,0.688206,0.591380,-0.020597,-0.810561
3,-0.460281,1.041726,0.042455,-0.665405,0.688206,0.510777,-1.737858,0.345325
4,-0.460281,1.041726,-2.667947,-1.127749,0.688206,0.510777,-0.908836,-0.810561
...,...,...,...,...,...,...,...,...
17961,-1.707547,0.067059,0.042455,-0.344061,0.688206,0.591380,-1.066745,0.114148
17962,-1.707547,-1.394942,0.042455,0.891875,0.688206,-1.343079,-0.020597,-0.810561
17963,-0.210828,-0.907608,0.042455,-0.843071,-1.455326,-1.504284,0.926858,0.576502
17964,1.036438,0.554393,0.042455,-0.946220,0.688206,0.510777,-0.020597,-0.348206
17965,4.029875,-0.907608,0.042455,-0.946220,0.688206,-1.472043,-0.020597,-0.810561

## CREATING MODEL WITH THE HELP OF ONE_HOT_ENCODING

In [58]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [59]:
X_train, X_test, y_train, y_test = train_test_split(one_hot_encoding, y, test_size=0.33, random_state=42)

In [60]:
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [61]:
y_pred = model.predict(X_test)

In [62]:
y_pred

array([22211.67805925, 15037.33325529, 16540.89418284, ...,
       15095.04684122, 12870.16427509, 15253.28175323], shape=(5878,))

In [63]:
y_test

9891     22975
13006    18000
15284    18500
6399      9985
8182      7998
         ...
12200    10470
7226     13998
11523    15199
13684    12290
9454     17990
Name: price, Length: 5878, dtype: int64

In [64]:
r2 = r2_score(y_pred,y_test)

In [65]:
r2

0.8028127599759631