In [52]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

## load the data set

In [53]:
df = pd.read_csv(r'C:\CODING\MACHINE LEARNING\hantavirus_environmental.csv')

## EDA

In [54]:
df.head()

,iso3,region,latitude,longitude,biome,year,quarter,avg_temp_c,rainfall_mm,humidity_pct,ndvi,rodent_abundance_index,rodent_host_species,deforestation_km2,exposure_setting
0,ARG,Patagonia,-42.0,-71.0,Temperate forest,2010,1,8.5,247.9,83.6,0.508,0.806,Oligoryzomys longicaudatus,3.91,Rural
1,ARG,Patagonia,-42.0,-71.0,Temperate forest,2010,2,14.2,218.5,72.2,0.504,0.679,Oligoryzomys longicaudatus,2.78,Peri-urban
2,ARG,Patagonia,-42.0,-71.0,Temperate forest,2010,3,13.9,192.8,55.3,0.339,0.552,Oligoryzomys longicaudatus,1.81,Rural
3,ARG,Patagonia,-42.0,-71.0,Temperate forest,2010,4,17.2,378.8,59.7,0.628,0.599,Oligoryzomys longicaudatus,3.48,Rural
4,ARG,Patagonia,-42.0,-71.0,Temperate forest,2011,1,5.2,198.1,67.1,0.389,0.613,Oligoryzomys longicaudatus,2.02,Rural

In [55]:
df.isnull().sum()

iso3                      0
region                    0
latitude                  0
longitude                 0
biome                     0
year                      0
quarter                   0
avg_temp_c                0
rainfall_mm               0
humidity_pct              0
ndvi                      0
rodent_abundance_index    0
rodent_host_species       0
deforestation_km2         0
exposure_setting          0
dtype: int64

In [56]:
df.duplicated().sum()

np.int64(0)

In [57]:
df.describe()

,latitude,longitude,year,quarter,avg_temp_c,rainfall_mm,humidity_pct,ndvi,rodent_abundance_index,deforestation_km2
count,896.000000,896.00000,896.000000,896.000000,896.000000,896.000000,896.000000,896.000000,896.000000,896.000000
mean,11.542857,-10.65000,2017.500000,2.500000,11.258036,252.834598,65.850335,0.546545,0.673340,3.425112
std,40.823500,82.94084,4.612347,1.118658,7.176808,217.756306,14.122252,0.169184,0.178733,1.428258
min,-45.600000,-122.30000,2010.000000,1.000000,-8.800000,0.000000,20.000000,0.251000,0.301000,0.570000
25%,-34.600000,-72.10000,2013.750000,1.750000,6.500000,100.600000,60.200000,0.405750,0.526750,2.257500
50%,35.400000,-46.20000,2017.500000,2.500000,11.700000,195.350000,67.600000,0.552500,0.672000,3.360000
75%,47.600000,56.00000,2021.250000,3.250000,16.200000,337.700000,75.250000,0.690000,0.825000,4.590000
max,63.100000,127.00000,2025.000000,4.000000,29.700000,1673.200000,98.000000,0.850000,1.000000,6.390000

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 896 entries, 0 to 895
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   iso3                    896 non-null    str
 1   region                  896 non-null    str
 2   latitude                896 non-null    float64
 3   longitude               896 non-null    float64
 4   biome                   896 non-null    str
 5   year                    896 non-null    int64
 6   quarter                 896 non-null    int64
 7   avg_temp_c              896 non-null    float64
 8   rainfall_mm             896 non-null    float64
 9   humidity_pct            896 non-null    float64
 10  ndvi                    896 non-null    float64
 11  rodent_abundance_index  896 non-null    float64
 12  rodent_host_species     896 non-null    str
 13  deforestation_km2       896 non-null    float64
 14  exposure_setting        896 non-null    str
dtypes: float64(8), int64(2), str(5)
memory usage: 105.1 KB

## droping the main thing that we have to find

In [59]:
x = df.drop(['rodent_abundance_index'],axis=1)
y = df['rodent_abundance_index']

In [60]:
x

,iso3,region,latitude,longitude,biome,year,quarter,avg_temp_c,rainfall_mm,humidity_pct,ndvi,rodent_host_species,deforestation_km2,exposure_setting
0,ARG,Patagonia,-42.0,-71.0,Temperate forest,2010,1,8.5,247.9,83.6,0.508,Oligoryzomys longicaudatus,3.91,Rural
1,ARG,Patagonia,-42.0,-71.0,Temperate forest,2010,2,14.2,218.5,72.2,0.504,Oligoryzomys longicaudatus,2.78,Peri-urban
2,ARG,Patagonia,-42.0,-71.0,Temperate forest,2010,3,13.9,192.8,55.3,0.339,Oligoryzomys longicaudatus,1.81,Rural
3,ARG,Patagonia,-42.0,-71.0,Temperate forest,2010,4,17.2,378.8,59.7,0.628,Oligoryzomys longicaudatus,3.48,Rural
4,ARG,Patagonia,-42.0,-71.0,Temperate forest,2011,1,5.2,198.1,67.1,0.389,Oligoryzomys longicaudatus,2.02,Rural
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
891,RUS,Bashkortostan,54.7,56.0,Forest steppe,2024,4,6.9,182.6,62.3,0.434,Myodes glareolus,3.31,Rural
892,RUS,Bashkortostan,54.7,56.0,Forest steppe,2025,1,-1.9,161.9,63.8,0.405,Myodes glareolus,4.27,Rural
893,RUS,Bashkortostan,54.7,56.0,Forest steppe,2025,2,1.8,71.1,56.4,0.251,Myodes glareolus,6.25,Peri-urban
894,RUS,Bashkortostan,54.7,56.0,Forest steppe,2025,3,0.6,158.9,67.1,0.556,Myodes glareolus,5.43,Rural
895,RUS,Bashkortostan,54.7,56.0,Forest steppe,2025,4,6.7,160.1,63.8,0.729,Myodes glareolus,2.94,Peri-urban

In [61]:
y

0      0.806
1      0.679
2      0.552
3      0.599
4      0.613
       ...
891    0.998
892    0.939
893    0.883
894    0.771
895    0.901
Name: rodent_abundance_index, Length: 896, dtype: float64

## perfoming one-hot_encoding

In [62]:
df.columns

Index(['iso3', 'region', 'latitude', 'longitude', 'biome', 'year', 'quarter',
       'avg_temp_c', 'rainfall_mm', 'humidity_pct', 'ndvi',
       'rodent_abundance_index', 'rodent_host_species', 'deforestation_km2',
       'exposure_setting'],
      dtype='str')

In [63]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 896 entries, 0 to 895
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   iso3                    896 non-null    str
 1   region                  896 non-null    str
 2   latitude                896 non-null    float64
 3   longitude               896 non-null    float64
 4   biome                   896 non-null    str
 5   year                    896 non-null    int64
 6   quarter                 896 non-null    int64
 7   avg_temp_c              896 non-null    float64
 8   rainfall_mm             896 non-null    float64
 9   humidity_pct            896 non-null    float64
 10  ndvi                    896 non-null    float64
 11  rodent_abundance_index  896 non-null    float64
 12  rodent_host_species     896 non-null    str
 13  deforestation_km2       896 non-null    float64
 14  exposure_setting        896 non-null    str
dtypes: float64(8), int64(2), str(5)
memory usage: 105.1 KB

In [64]:
one_hot_enododing = pd.get_dummies(x,columns=[ 'iso3','region','biome','rodent_host_species','exposure_setting' ],drop_first=True)

In [65]:
one_hot_enododing

,latitude,longitude,year,quarter,avg_temp_c,rainfall_mm,humidity_pct,ndvi,deforestation_km2,iso3_BRA,...,biome_Temperate mixed,biome_Temperate rain,biome_Valdivian forest,biome_Warm temperate,rodent_host_species_Myodes glareolus,rodent_host_species_Necromys lasiurus,rodent_host_species_Oligoryzomys flavescens,rodent_host_species_Oligoryzomys longicaudatus,rodent_host_species_Peromyscus maniculatus,exposure_setting_Rural
0,-42.0,-71.0,2010,1,8.5,247.9,83.6,0.508,3.91,False,...,False,False,False,False,False,False,False,True,False,True
1,-42.0,-71.0,2010,2,14.2,218.5,72.2,0.504,2.78,False,...,False,False,False,False,False,False,False,True,False,False
2,-42.0,-71.0,2010,3,13.9,192.8,55.3,0.339,1.81,False,...,False,False,False,False,False,False,False,True,False,True
3,-42.0,-71.0,2010,4,17.2,378.8,59.7,0.628,3.48,False,...,False,False,False,False,False,False,False,True,False,True
4,-42.0,-71.0,2011,1,5.2,198.1,67.1,0.389,2.02,False,...,False,False,False,False,False,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
891,54.7,56.0,2024,4,6.9,182.6,62.3,0.434,3.31,False,...,False,False,False,False,True,False,False,False,False,True
892,54.7,56.0,2025,1,-1.9,161.9,63.8,0.405,4.27,False,...,False,False,False,False,True,False,False,False,False,True
893,54.7,56.0,2025,2,1.8,71.1,56.4,0.251,6.25,False,...,False,False,False,False,True,False,False,False,False,False
894,54.7,56.0,2025,3,0.6,158.9,67.1,0.556,5.43,False,...,False,False,False,False,True,False,False,False,False,True
895,54.7,56.0,2025,4,6.7,160.1,63.8,0.729,2.94,False,...,False,False,False,False,True,False,False,False,False,False

In [66]:
one_hot_enododing = one_hot_enododing.astype(int)

In [67]:
one_hot_enododing

,latitude,longitude,year,quarter,avg_temp_c,rainfall_mm,humidity_pct,ndvi,deforestation_km2,iso3_BRA,...,biome_Temperate mixed,biome_Temperate rain,biome_Valdivian forest,biome_Warm temperate,rodent_host_species_Myodes glareolus,rodent_host_species_Necromys lasiurus,rodent_host_species_Oligoryzomys flavescens,rodent_host_species_Oligoryzomys longicaudatus,rodent_host_species_Peromyscus maniculatus,exposure_setting_Rural
0,-42,-71,2010,1,8,247,83,0,3,0,...,0,0,0,0,0,0,0,1,0,1
1,-42,-71,2010,2,14,218,72,0,2,0,...,0,0,0,0,0,0,0,1,0,0
2,-42,-71,2010,3,13,192,55,0,1,0,...,0,0,0,0,0,0,0,1,0,1
3,-42,-71,2010,4,17,378,59,0,3,0,...,0,0,0,0,0,0,0,1,0,1
4,-42,-71,2011,1,5,198,67,0,2,0,...,0,0,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
891,54,56,2024,4,6,182,62,0,3,0,...,0,0,0,0,1,0,0,0,0,1
892,54,56,2025,1,-1,161,63,0,4,0,...,0,0,0,0,1,0,0,0,0,1
893,54,56,2025,2,1,71,56,0,6,0,...,0,0,0,0,1,0,0,0,0,0
894,54,56,2025,3,0,158,67,0,5,0,...,0,0,0,0,1,0,0,0,0,1
895,54,56,2025,4,6,160,63,0,2,0,...,0,0,0,0,1,0,0,0,0,0

## now doing label encoding

In [68]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

columns = ['iso3','region','biome','rodent_host_species','exposure_setting' ]
xlabel = x.copy()
label_encoder = {}

for col in columns:
    le = LabelEncoder()
    xlabel[col] = le.fit_transform(xlabel[col].astype(str)) #convert to str into null values 
    
    label_encoder[col] = le

In [69]:
xlabel

,iso3,region,latitude,longitude,biome,year,quarter,avg_temp_c,rainfall_mm,humidity_pct,ndvi,rodent_host_species,deforestation_km2,exposure_setting
0,0,11,-42.0,-71.0,9,2010,1,8.5,247.9,83.6,0.508,4,3.91,1
1,0,11,-42.0,-71.0,9,2010,2,14.2,218.5,72.2,0.504,4,2.78,0
2,0,11,-42.0,-71.0,9,2010,3,13.9,192.8,55.3,0.339,4,1.81,1
3,0,11,-42.0,-71.0,9,2010,4,17.2,378.8,59.7,0.628,4,3.48,1
4,0,11,-42.0,-71.0,9,2011,1,5.2,198.1,67.1,0.389,4,2.02,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
891,7,2,54.7,56.0,5,2024,4,6.9,182.6,62.3,0.434,1,3.31,1
892,7,2,54.7,56.0,5,2025,1,-1.9,161.9,63.8,0.405,1,4.27,1
893,7,2,54.7,56.0,5,2025,2,1.8,71.1,56.4,0.251,1,6.25,0
894,7,2,54.7,56.0,5,2025,3,0.6,158.9,67.1,0.556,1,5.43,1
895,7,2,54.7,56.0,5,2025,4,6.7,160.1,63.8,0.729,1,2.94,0

## DOING STANDARD SCALING TO CONVERT LARGE NUMERIC NUMBER INTO SMALLE ONE WITH THE HELP OF ONE_HOT_ENCODING

In [70]:
from sklearn.preprocessing import StandardScaler

In [71]:
numeric_only =['latitude','longitude','year','quarter','avg_temp_c','rainfall_mm','humidity_pct','ndvi','deforestation_km2']

scaler = StandardScaler()

one_hot_enododing[numeric_only] = scaler.fit_transform(one_hot_enododing[numeric_only])

In [72]:
one_hot_enododing.head()

,latitude,longitude,year,quarter,avg_temp_c,rainfall_mm,humidity_pct,ndvi,deforestation_km2,iso3_BRA,...,biome_Temperate mixed,biome_Temperate rain,biome_Valdivian forest,biome_Warm temperate,rodent_host_species_Myodes glareolus,rodent_host_species_Necromys lasiurus,rodent_host_species_Oligoryzomys flavescens,rodent_host_species_Oligoryzomys longicaudatus,rodent_host_species_Peromyscus maniculatus,exposure_setting_Rural
0,-1.327945,-0.730492,-1.626978,-1.341641,-0.407423,-0.024835,1.246999,0.0,0.049814,0,...,0,0,0,0,0,0,0,1,0,1
1,-1.327945,-0.730492,-1.626978,-0.447214,0.443843,-0.158111,0.467348,0.0,-0.636851,0,...,0,0,0,0,0,0,0,1,0,0
2,-1.327945,-0.730492,-1.626978,0.447214,0.301965,-0.277600,-0.737568,0.0,-1.323515,0,...,0,0,0,0,0,0,0,1,0,1
3,-1.327945,-0.730492,-1.626978,1.341641,0.869476,0.577204,-0.454058,0.0,0.049814,0,...,0,0,0,0,0,0,0,1,0,1
4,-1.327945,-0.730492,-1.410048,-1.341641,-0.833057,-0.250026,0.112961,0.0,-0.636851,0,...,0,0,0,0,0,0,0,1,0,1

## doing standard scaling with the help of label Encoding

In [73]:
df.columns

Index(['iso3', 'region', 'latitude', 'longitude', 'biome', 'year', 'quarter',
       'avg_temp_c', 'rainfall_mm', 'humidity_pct', 'ndvi',
       'rodent_abundance_index', 'rodent_host_species', 'deforestation_km2',
       'exposure_setting'],
      dtype='str')

In [75]:
xlabel[['iso3', 'region', 'latitude', 'longitude', 'biome', 'year', 'quarter',
       'avg_temp_c', 'rainfall_mm', 'humidity_pct', 'ndvi',
        'rodent_host_species', 'deforestation_km2',
       'exposure_setting']] = scaler.fit_transform(xlabel[['iso3', 'region', 'latitude', 'longitude', 'biome', 'year', 'quarter',
       'avg_temp_c', 'rainfall_mm', 'humidity_pct', 'ndvi',
        'rodent_host_species', 'deforestation_km2',
       'exposure_setting']])

In [77]:
xlabel.head()

,iso3,region,latitude,longitude,biome,year,quarter,avg_temp_c,rainfall_mm,humidity_pct,ndvi,rodent_host_species,deforestation_km2,exposure_setting
0,-1.313971,1.116313,-1.312302,-0.728033,0.620174,-1.626978,-1.341641,-0.384513,-0.022674,1.257560,-0.227955,0.957704,0.339686,0.741736
1,-1.313971,1.116313,-1.312302,-0.728033,0.620174,-1.626978,-0.447214,0.410156,-0.157762,0.449872,-0.251611,0.957704,-0.451929,-1.348188
2,-1.313971,1.116313,-1.312302,-0.728033,0.620174,-1.626978,0.447214,0.368331,-0.275850,-0.747489,-1.227428,0.957704,-1.131458,0.741736
3,-1.313971,1.116313,-1.312302,-0.728033,0.620174,-1.626978,1.341641,0.828402,0.578793,-0.435750,0.481730,0.957704,0.038452,0.741736
4,-1.313971,1.116313,-1.312302,-0.728033,0.620174,-1.410048,-1.341641,-0.844584,-0.251498,0.088539,-0.931726,0.957704,-0.984343,0.741736

## now creating model with the help of one_hot_ncoding

In [78]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [79]:
X_train, X_test, y_train, y_test = train_test_split(one_hot_enododing, y, test_size=0.33, random_state=42)

In [80]:
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

## making predection

In [81]:
y_pred = model.predict(X_test)

In [82]:
y_pred

array([0.5896694 , 0.74101921, 0.61389588, 0.6326661 , 0.70226703,
       0.70417325, 0.7708624 , 0.65029196, 0.59454421, 0.61872474,
       0.60943126, 0.64187556, 0.71415327, 0.67368977, 0.66220996,
       0.69354655, 0.74702434, 0.58774067, 0.76461602, 0.68409178,
       0.73172508, 0.64681876, 0.52123058, 0.58146594, 0.66873651,
       0.56769249, 0.69983494, 0.62770431, 0.76323603, 0.65255787,
       0.55725968, 0.65132988, 0.66305469, 0.63115974, 0.55227616,
       0.65059634, 0.65634597, 0.54064466, 0.68161868, 0.6749443 ,
       0.75343563, 0.68295578, 0.57634142, 0.70242545, 0.69899684,
       0.6275645 , 0.59141227, 0.68271074, 0.57113355, 0.72382569,
       0.61130421, 0.74440096, 0.71709579, 0.67957143, 0.69821778,
       0.61847691, 0.60706251, 0.73759408, 0.54258253, 0.74424024,
       0.65314562, 0.72544858, 0.69645789, 0.72114848, 0.54009351,
       0.73902986, 0.62372573, 0.6827702 , 0.64385334, 0.56380193,
       0.78369403, 0.77009465, 0.72616788, 0.63664526, 0.65131996,
       0.55946027, 0.60181382, 0.72703785, 0.68742259, 0.69823076,
       0.66012366, 0.60189113, 0.79502379, 0.61360663, 0.69778484,
       0.75610068, 0.57762572, 0.77664914, 0.75207787, 0.65996823,
       0.67669453, 0.65951783, 0.59754038, 0.6244306 , 0.63486376,
       0.69889437, 0.66461554, 0.63937198, 0.57186531, 0.59125212,
       0.65888505, 0.54893844, 0.72647021, 0.78229555, 0.54044944,
       0.79399119, 0.66461679, 0.63877261, 0.69339382, 0.58349013,
       0.70554194, 0.58184673, 0.62906045, 0.60278376, 0.70220929,
       0.7536939 , 0.69104746, 0.75329606, 0.57888209, 0.69578346,
       0.64198422, 0.5713158 , 0.66027464, 0.58672035, 0.66682611,
       0.61707669, 0.69171037, 0.60191261, 0.61971984, 0.62796233,
       0.68452616, 0.58417625, 0.73524321, 0.64691162, 0.63655208,
       0.64915744, 0.75911588, 0.60676353, 0.64460039, 0.73505756,
       0.70266099, 0.66937916, 0.66623236, 0.58742036, 0.80963378,
       0.66523328, 0.57395134, 0.72994337, 0.67313892, 0.62625138,
       0.58965566, 0.72603865, 0.67243575, 0.69956977, 0.62592558,
       0.64383029, 0.65058571, 0.64417602, 0.69444714, 0.58875937,
       0.75834318, 0.71090363, 0.71076395, 0.72404264, 0.63056022,
       0.74075483, 0.6217085 , 0.78257826, 0.61146417, 0.68870162,
       0.685335  , 0.6853019 , 0.61910471, 0.69414202, 0.72226669,
       0.66364775, 0.67061373, 0.64569311, 0.62394456, 0.60016521,
       0.68455484, 0.76100098, 0.58276843, 0.74641765, 0.73518557,
       0.6387673 , 0.6960121 , 0.67861473, 0.74678572, 0.73683019,
       0.59405471, 0.60750771, 0.63117305, 0.627156  , 0.62131693,
       0.72185808, 0.71548051, 0.69498649, 0.67037596, 0.64979914,
       0.58485273, 0.69259825, 0.68191744, 0.66250888, 0.76929983,
       0.66258107, 0.61752726, 0.62888141, 0.68901123, 0.70249895,
       0.72439008, 0.71574122, 0.71042081, 0.53599293, 0.6579252 ,
       0.62553085, 0.54811112, 0.65299076, 0.7360611 , 0.70436792,
       0.70410394, 0.49966959, 0.72356021, 0.73434706, 0.68571768,
       0.65351801, 0.71408515, 0.74683079, 0.78102987, 0.60155401,
       0.64468198, 0.56280556, 0.68155989, 0.68720302, 0.67070937,
       0.59684464, 0.64625516, 0.77509981, 0.74806528, 0.67495983,
       0.73685117, 0.75398916, 0.58889995, 0.6599601 , 0.60972011,
       0.67430523, 0.67023155, 0.59781963, 0.58873773, 0.62698858,
       0.59504533, 0.64842817, 0.7111965 , 0.77470987, 0.6087375 ,
       0.63245919, 0.70140643, 0.61436634, 0.65788718, 0.60256679,
       0.68966615, 0.68657872, 0.65048752, 0.70349286, 0.69341866,
       0.63592133, 0.77722296, 0.70114148, 0.73818049, 0.59784235,
       0.70540661, 0.6344014 , 0.77011938, 0.63595291, 0.72640305,
       0.6504152 , 0.63371368, 0.73957999, 0.57825116, 0.67475279,
       0.5891691 , 0.5843558 , 0.61040737, 0.69351394, 0.62430036,
       0.67905671, 0.70309552, 0.76111716, 0.53741563, 0.73537875,
       0.67814108, 0.7791899 , 0.74819039, 0.63031582, 0.71306415,
       0.62168282])

In [83]:
y_test

711    0.539
440    0.689
525    0.430
722    0.592
39     0.774
       ...
506    0.849
381    0.467
140    0.757
173    0.422
6      0.803
Name: rodent_abundance_index, Length: 296, dtype: float64

In [84]:
r2 = r2_score(y_pred,y_test)

In [85]:
r2

-7.825306286300542

## doing predection with label encoding

In [88]:
X_train, X_test, y_train, y_test = train_test_split(xlabel, y, test_size=0.33, random_state=42)

In [89]:
model2 = LinearRegression()
model2.fit(X_train,y_train)

LinearRegression()

In [92]:
y_pred = model2.predict(X_test)

In [93]:
y_pred

array([0.62291298, 0.76406702, 0.6029632 , 0.66445749, 0.65724125,
       0.68066557, 0.7475154 , 0.64276023, 0.65394972, 0.61543703,
       0.60078979, 0.65183027, 0.70982147, 0.75118735, 0.67451863,
       0.65446152, 0.73078442, 0.60012555, 0.71980072, 0.69571513,
       0.72157262, 0.63304247, 0.58865392, 0.60664052, 0.64434269,
       0.59910927, 0.66545455, 0.63674193, 0.73235845, 0.66374633,
       0.56849331, 0.63128329, 0.67405745, 0.68949633, 0.61899705,
       0.68820577, 0.61868235, 0.59404647, 0.63333215, 0.70959636,
       0.74428138, 0.69129679, 0.58601156, 0.70918791, 0.69846346,
       0.62352057, 0.60045203, 0.68147601, 0.63688993, 0.68130023,
       0.62929509, 0.74698123, 0.71681075, 0.68970356, 0.68770309,
       0.62359344, 0.58411313, 0.70094757, 0.59838258, 0.70129944,
       0.67565584, 0.75060553, 0.68552822, 0.71473791, 0.60523595,
       0.73790716, 0.62259828, 0.6850569 , 0.61776663, 0.59331146,
       0.77247914, 0.73418856, 0.74704946, 0.58446302, 0.61725104,
       0.57467097, 0.58073589, 0.77239384, 0.71940752, 0.75095814,
       0.61258963, 0.58524179, 0.74354788, 0.57177444, 0.69968973,
       0.74339737, 0.63827136, 0.74068609, 0.74812574, 0.74816236,
       0.67079057, 0.63200682, 0.63640955, 0.64930375, 0.62003775,
       0.68666349, 0.6890423 , 0.65326947, 0.60033856, 0.60542319,
       0.60472584, 0.57538906, 0.69197468, 0.74709698, 0.56462279,
       0.77571802, 0.69057724, 0.65659068, 0.6711249 , 0.64884165,
       0.65382223, 0.65080033, 0.61434739, 0.58397724, 0.68553785,
       0.72430492, 0.69769924, 0.72811602, 0.57659223, 0.73420397,
       0.63050738, 0.6359829 , 0.65364241, 0.61225883, 0.6682883 ,
       0.62741021, 0.69371384, 0.59938326, 0.61967927, 0.63140974,
       0.68462047, 0.57080756, 0.72567333, 0.64748261, 0.58806094,
       0.60378472, 0.74959211, 0.68893696, 0.66533707, 0.69956953,
       0.70920162, 0.60414896, 0.66760574, 0.59350663, 0.74385881,
       0.68923095, 0.62866517, 0.68525839, 0.64702101, 0.62733831,
       0.60063068, 0.71117591, 0.7105086 , 0.70604988, 0.62364082,
       0.64287382, 0.67385963, 0.64600777, 0.71832188, 0.59593183,
       0.72895694, 0.71804954, 0.71574755, 0.71363025, 0.62433075,
       0.70210871, 0.62102384, 0.73876001, 0.56841601, 0.67129265,
       0.6850326 , 0.68812195, 0.64045841, 0.63696879, 0.71849858,
       0.62692446, 0.64177314, 0.64460726, 0.60041867, 0.59534447,
       0.69374945, 0.76859937, 0.61384344, 0.73424935, 0.73668687,
       0.63649039, 0.69250195, 0.63782702, 0.71009147, 0.70394882,
       0.63527427, 0.68055148, 0.61836001, 0.63074591, 0.5965762 ,
       0.71485051, 0.70900914, 0.69921484, 0.66035456, 0.62858224,
       0.59472073, 0.72382212, 0.64840494, 0.69580344, 0.79456653,
       0.62877012, 0.64964608, 0.61010702, 0.71017261, 0.70881875,
       0.74503349, 0.73710085, 0.68379384, 0.56583502, 0.66596645,
       0.5978056 , 0.57073901, 0.63517309, 0.70922263, 0.70728665,
       0.70333871, 0.57719048, 0.71753053, 0.70117815, 0.69655445,
       0.72195587, 0.71614414, 0.72154154, 0.76814262, 0.56377153,
       0.65666579, 0.60004002, 0.64215027, 0.70498119, 0.64572761,
       0.58756128, 0.5847918 , 0.77139857, 0.77370104, 0.70469796,
       0.72059725, 0.76174119, 0.5776154 , 0.65788203, 0.59587594,
       0.68475268, 0.66072451, 0.61842468, 0.65779856, 0.62364231,
       0.60474774, 0.65066857, 0.72748966, 0.75787737, 0.64130712,
       0.67976298, 0.65398629, 0.61945193, 0.6406076 , 0.60423449,
       0.68983118, 0.66805286, 0.64801189, 0.71254664, 0.71844055,
       0.63596562, 0.7805435 , 0.6993927 , 0.75424568, 0.61008541,
       0.70689395, 0.64087221, 0.75270405, 0.62977525, 0.67946236,
       0.65925526, 0.59188183, 0.7116704 , 0.55817215, 0.67389621,
       0.58818972, 0.56461863, 0.61733727, 0.68554986, 0.59864659,
       0.68543627, 0.66477187, 0.75783689, 0.59119292, 0.70173535,
       0.70377221, 0.77001806, 0.74658678, 0.62629588, 0.69649309,
       0.59412249])

In [94]:
y_test

711    0.539
440    0.689
525    0.430
722    0.592
39     0.774
       ...
506    0.849
381    0.467
140    0.757
173    0.422
6      0.803
Name: rodent_abundance_index, Length: 296, dtype: float64

In [95]:
r2 = r2_score(y_pred,y_test)

In [96]:
r2

-9.410791657716166